- hosts: localhost
  vars:
  pre_tasks:
  - name: Update Dnf
    become: true
    dnf:
      update_cache: yes
      state: present
    tags:
      - install
      - core
  tasks:
    - include_tasks: tasks/git-setup.yml
      tags:
        - git
    - include_tasks: tasks/zsh-setup.yml
      tags: &tags_for_zsh_tasks ['install', 'productivity', 'dotfiles', 'zsh']
    - include_tasks: tasks/node-setup.yml
      tags: 
        - node
    #- include_tasks: tasks/rust-setup.yml

