- name: determine shell in which we are running
  block:

    - name: set default found path
      set_fact:
        found_path: ''

    - name: test for shells
      command: "which {{ item }}"
      with_items:
        - zsh
      register: shell_path

    - name: set found path
      set_fact:
        found_path: "{{ shell_path.results | selectattr('stdout', 'defined') | map(attribute = 'stdout') | list | first }}"
      when: shell_path.results | selectattr('stdout', 'defined') | map(attribute = 'stdout') | list | length > 0

    - name: set zsh command
      set_fact:
        user_shell: { 'command': '{{ found_path }} -ic', 'alias': 'zsh' }
        
  tags:
    - install
    - node

- name: Check NVM Version
  shell: "{{ user_shell.command + ' \"source ~/.zshrc\"' }}"
  register: nvm_version_response
  changed_when: "nvm_version_response.rc != 0"
  tags:
    - install
    - node

- name: Check NVM Version
  shell: "{{ user_shell.command + ' \"nvm --version\"' }}"
  register: nvm_version_response
  changed_when: "nvm_version_response.rc != 0"
  tags:
    - install
    - node

- name: Install Node LTS
  shell: "{{ user_shell.command + ' \"nvm install --lts\"' }}"
  register: node_version_response
  changed_when: "'already installed' not in node_version_response.stderr"
  tags:
    - install
    - node

- name: Install Node 14
  shell: "{{ user_shell.command + ' \"nvm install 14\"' }}"
  register: node_version_response
  changed_when: "'already installed' not in node_version_response.stderr"
  tags:
    - install
    - node
