- name: Install ZSH
  dnf: name=zsh
  tags: &tags_for_zsh_tasks ['install', 'productivity', 'dotfiles', 'zsh']
  become: true

- name: Install User Utils
  dnf: name=util-linux-user
  tags: *tags_for_zsh_tasks
  become: true

- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks
  become: true

- name: Check that the somefile.conf exits
  stat:
    path: /home/dani/.oh-my-zsh
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False
  #become_user: dani

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks
  #become_user: dani
  
- name: Install zsh-nvm
  ansible.builtin.git:
    repo: 'https://github.com/lukechilds/zsh-nvm.git'
    dest: "~/.oh-my-zsh/plugins/zsh-nvm"
  tags: *tags_for_zsh_tasks
  #become_user: dani
  
- name: Update zshrc
  shell: sed -i 's/(git/(git zsh-autosuggestions zsh-nvm/' ~/.zshrc
  tags: *tags_for_zsh_tasks
  #become_user: dani
  
